# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30, null=True)),
                ('selected_column', models.CharField(max_length=30, null=True)),
                ('features', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
